seleniumGrid=false
gridURL=http://localhost:4444/wd/hub

#Application URL
#url = https://opensource-demo.orangehrmlive.com/
url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login?lang=en

#Browser Configuration
#browser = chrome

#Credentials
username = Admin
password = admin123

#ImplicitWait (in seconds)
implicitWait =30

#ExplicitWait
explicitWait = 30