seleniumGrid=false
gridURL=http://localhost:4444/wd/hub

#Application URL
#url = https://opensource-demo.orangehrmlive.com/
url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login?lang=en

#Browser Configuration
#browser = chrome

#Credentials
#username = Admin
#password = admin123

#ImplicitWait (in seconds)
implicitWait =30

#ExplicitWait
explicitWait = 30

#To impelement selenium grid testing...

#first open cmd on seleniumgrid.jar location and then run command-
# "java -jar selenium-server-4.49.0.jar hub"
# and then open the new cmd on seleniumgrid.jar location and then run command-
# "java -jar selenium-server-4.49.0.jar node --port 5555"
#
#url for seleniumgrid localhost- http://localhost:4444/ui/#

// for running test through docker
// docker run -d --name selenium-hub --net selenium-grid -p 4444:4444 selenium/hub:latest

// to configure selenium grid with docker
// docker pull selenium/hub:4.49.0]

// to create chrome node
// docker pull selenium/node-chrome:4.49.0

// to create firefox node 
// docker pull selenium/node-firefox:4.49.0

// same for edge

// to create local host
// docker network create selenium-grid

// to create selenium hub on local host
// docker run -d -p 4444:4444 --net selenium-grid --name selenium-hub selenium/hub:4.49.0

// to create selenium nodes of chrome, firefox, edge
// docker run -d --name selenium-chrome --net selenium-grid -e SE_EVENT_BUS_HOST=selenium-hub selenium/node-chrome:4.49.0
// docker run -d --name selenium-firefox --net selenium-grid -e SE_EVENT_BUS_HOST=selenium-hub selenium/node-firefox:4.49.0
// docker run -d --name selenium-edge --net selenium-grid -e SE_EVENT_BUS_HOST=selenium-hub selenium/node-edge:4.49.0